context:
  name: torch_memory_saver
  version: "0.0.9"
  cuda_build_string: cuda_${{ cuda_compiler_version | version_to_buildstring }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/torch_memory_saver-${{ version }}.tar.gz
  sha256: 3bbf76391fb16870b1b0df279fc281c8a05ef8f8809400b309b0a8240e8ee5ba

build:
  skip:
    - cuda_compiler_version == "None"
    - not linux
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  string: ${{ cuda_build_string }}py${{ python | version_to_buildstring }}h${{ hash }}_${{ build_number }}
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cuda') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - make
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pytorch * [build=cuda*]

tests:
  - python:
      imports:
        - torch_memory_saver
      pip_check: true

about:
  homepage: https://github.com/fzyzcjy/torch_memory_saver
  summary: A PyTorch library that allows tensor memory to be temporarily released and resumed later.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shermansiu
